# Generated by Django 3.0.3 on 2020-02-26 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.trucks', '0004_auto_20200224_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='VIN',
            field=models.CharField(error_messages={'unique': 'This VIN has already been registered.'}, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_VIN', message='Invalid VIN. Please check your VIN.', regex='^[a-zA-Z0-9]{17}$')]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_year', message='Year must be a 4-digit number.', regex='^[0-9]{4}$')]),
        ),
    ]
