# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 15:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.boats', '0002_auto_20200224_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='HIN',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_HIN', message=b'HIN must be alphanumeric.', regex=b'^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='boat',
            name='currentHours',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='boat',
            name='length',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='boat',
            name='make',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='boat',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='boat',
            name='nextService',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='boat',
            name='serviceInterval',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='boat',
            name='width',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='boat',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
