# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 05:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={b'blank': b'Enter a name.', b'invalid': b'Name must not have more than 20 characters.'}, max_length=10)),
                ('email', models.CharField(error_messages={b'blank': b'Enter an email address', b'invalid': b'Enter a valid email address.'}, max_length=30, unique=True, validators=[django.core.validators.EmailValidator(code=b'invalid_email', message=b'Email must be valid.')])),
                ('password', models.CharField(error_messages={b'blank': b'Enter a password'}, max_length=30)),
            ],
        ),
    ]
