# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 15:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.EmailValidator(code=b'invalid_email', message=b'Email must be valid.')]),
        ),
        migrations.AlterField(
            model_name='auth',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
