# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0002_auto_20200224_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.EmailField(error_messages={b'unique': b'This email address has already been registered.'}, max_length=30, unique=True),
        ),
    ]
